---
:streams:
- :video_id: "REPLACEME"
  :title: "None"
  :description: "None"
  :width: 1920
  :height: 1080
  :short_url_key: "None"
  :signed_token: "None"
- :video_id: "d277da201df1359c8bec9629071ac35f"
  :title: "FSM School Part I by John Cowden"
  :description: "John Cowden presents Field Staff Members School - Part I"
  :width: 1280
  :height: 720
  :short_url_key: "johncowdenfsmschoolpartianzo"
  :signed_token: ""
- :video_id: "78af0c8b8f577b574a3a1125a761d602"
  :title: "FSM School Part II by John Cowden"
  :description: "John Cowden presents Field Staff Members School - Part II"
  :width: 1280
  :height: 720
  :short_url_key: "johncowdenfsmschoolpartiianzo"
  :signed_token: ""
- :video_id: "62510c43617d36d59b3160bbb3d0ce65"
  :title: "FSM School Part III by John Cowden"
  :description: "John Cowden presents Field Staff Members School - Part III"
  :width: 1280
  :height: 720
  :short_url_key: "johncowdenfsmschoolpartiiianzo"
  :signed_token: ""
- :video_id: "e27ce7a4623e6d495d7ad6ba3b636d6b"
  :title: "Admin Tools Part 1 by Fred King"
  :description: "Learn the Admins Tools you need to prosper"
  :width: 1280
  :height: 720
  :short_url_key: "fredkingadmintoolspart1anzo"
  :signed_token: "None"
