:streams:
- :title: "John Cowden Part I Dissem seminar ANZO"
  :video_id: "d277da201df1359c8bec9629071ac35f"
  :nbf: 1611971700
  :exp: 1612130400
  :short_url_key: "johncowdendissemseminarpartianzo"
  :signed_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4In0.eyJzdWIiOiJkMjc3ZGEyMDFkZjEzNTljOGJlYzk2MjkwNzFhYzM1ZiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4IiwiZXhwIjoiMTYxMjEzMDQwMCIsIm5iZiI6IjE2MTE5NzE3MDAifQ.Qf7PqDMqe4q-Bkrt2qUDR1Uh86JVTJK5SOBMKhzQptrF8w4ckaj_wTiibOs-pJtnqJ7eyHFzQcjICL_a8luA4uwzy78enu4ea2A-3R38dW7FQNU7sYLmQYvInHVtfk9og9B4NoXKYhCo3E3QdhPtHlkLRZnKaFge4wRy8UVsiHw4QsSNOI3pNb027kLLjs2L0ElVeaPwGI18N390Qqum79d159E9pE7keLqf3-_9OMJtzsyu1D6T1NvgZQtxowi4dwmvXkoTDw2TSFKTRvY9bbWIQt0TijIDrfuzV5iPxj-9_PkE9h3tgINXSoOnL0JJafYMEUxiyo5_covZlZDnwA"
- :title: "John Cowden Part II Dissem seminar ANZO"
  :video_id: "78af0c8b8f577b574a3a1125a761d602"
  :nbf: 1611971700
  :exp: 1612130400
  :short_url_key: "johncowdendissemseminarpartiianzo"
  :signed_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4In0.eyJzdWIiOiI3OGFmMGM4YjhmNTc3YjU3NGEzYTExMjVhNzYxZDYwMiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4IiwiZXhwIjoiMTYxMjEzMDQwMCIsIm5iZiI6IjE2MTE5NzE3MDAifQ.aIbsGRaDbXgIlAJ0quO_sq1IpInmmc8MPFyaKJ3JvCeVCy-VJxOu2RhHf9cvgt1MMZJx5VC6tArKLyG0sP-EczAO0vnKJAOvKCDMOV4Ih_Pt_QQsywhQIg_1UkdaL41K-n8ktGdr5uorolGcyVQHPcdRwjfmPuSOBkcDv8W6qetR4W-UsGL2-FcOVHQYOEZmBlf3RbV-eKv0slw8pTjxl_x4i_Uu71QuGCTkEjVmcJqvBuWiP6uKUffoyHG-FkoIrKmK3nX-RyQpM2dClpwaTHscMc-or6z8AFfugXjZV0_6rYjIHStN5NheYTFaqkOB95DQMjZq-s4kLQguCWGlmw"
