---
:streams:
- :video_id: "REPLACEME"
  :title: "None"
  :description: "None"
  :width: 1920
  :height: 1080
  :short_url_key: "None"
  :signed_token: "None"
- :video_id: "d277da201df1359c8bec9629071ac35f"
  :title: "FSM School Part I by John Cowden"
  :description: "John Cowden presents Field Staff Members School - Part I"
  :width: 1280
  :height: 720
  :short_url_key: "johncowdenfsmschoolpartianzo"
  :signed_token: ""
- :video_id: "78af0c8b8f577b574a3a1125a761d602"
  :title: "FSM School Part II by John Cowden"
  :description: "John Cowden presents Field Staff Members School - Part II"
  :width: 1280
  :height: 720
  :short_url_key: "johncowdenfsmschoolpartiianzo"
  :signed_token: ""
- :video_id: "62510c43617d36d59b3160bbb3d0ce65"
  :title: "FSM School Part III by John Cowden"
  :description: "John Cowden presents Field Staff Members School - Part III"
  :width: 1280
  :height: 720
  :short_url_key: "johncowdenfsmschoolpartiiianzo"
  :signed_token: ""
- :video_id: "632bdd83971d2bc470cfa26c134ff277"
  :title: "Admin Tools Part 1 by Fred King"
  :description: "Learn the Admins Tools you need to prosper"
  :width: 1280
  :height: 720
  :short_url_key: "fredkingadmintoolspart1anzo"
  :signed_token: "None"
- :video_id: "dcac6af7042e626ac5c3e56d2f058b6d"
  :title: "Admin Tools Part 2 by Fred King"
  :description: "Learn the Admins Tools you need to prosper"
  :width: 1280
  :height: 720
  :short_url_key: "fredkingadmintoolspart2anzo"
  :signed_token: "None"
- :video_id: "4b9fabfe341165bd060bf845e0b646f0"
  :title: "Briefing for ANZO OTVs with Mr Rabey"
  :description: "OTV Briefing - motivational - how you can save the planet"
  :width: 1280
  :height: 720
  :short_url_key: "mrrabeybriefingforanzootvs"
  :signed_token: "TBA"
- :video_id: "0008283875a0a67efc6d8681e56be889"
  :title: "Admin Tools Part 3 by Fred King"
  :description: "Learn the Admins Tools you need to prosper"
  :width: 1280
  :height: 720
  :short_url_key: "fredkingadmintoolspart3anzo"
  :signed_token: "None"
