---
:streams:
- :title: "John Cowden FSM School Part I Dissem seminar ANZO"
  :video_id: "d277da201df1359c8bec9629071ac35f"
  :nbf: 0
  :exp: 0
  :short_url_key: "johncowdenfsmschoolpartianzo"
  :signed_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4In0.eyJzdWIiOiJkMjc3ZGEyMDFkZjEzNTljOGJlYzk2MjkwNzFhYzM1ZiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4IiwiZXhwIjoiMTYxMjM0ODMzMCIsIm5iZiI6IjE2MTIzNDExMzAifQ.UkrMitW4xJaFdMFBN8LBs7D6xqvgVPYMEN_41J2HxrgNYDaBnGT1-dq2LrRistIqK1zDICZRX7agOCNONSKY_NtJJbQwaywVHt7f8JwCn306U-P9SsZoQwZEO3kRdCYqt08fncHjUdJbzXj9u_8RdwERGxAE1sMZ_N9DIv7AvcIHLjx8PNoBo1ItCHPGXbOlyHAb7pw8aglD8VGq5SJ733RdxINwn4-VABQw3MpJ9j2idKKXyLvuRQEO_X7aTj-h26i-rAmULlV4dvxBZdUxHkJWLxqKDaxqCeaqp-V_uykwlv2GtPEtELMY6f8YpiU6f7gcrYhAwYWUFtNMFlDEsg"
- :title: "John Cowden FSM School Part II ANZO"
  :video_id: "78af0c8b8f577b574a3a1125a761d602"
  :nbf: 0
  :exp: 0
  :short_url_key: "johncowdenfsmschoolpartiianzo"
  :signed_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4In0.eyJzdWIiOiI3OGFmMGM4YjhmNTc3YjU3NGEzYTExMjVhNzYxZDYwMiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4IiwiZXhwIjoiMTYxMjM0ODM2MSIsIm5iZiI6IjE2MTIzNDExNjEifQ.gQI82MNtM-sQ-uoT-R3RquKa7dJ62LbEa4xzqCicS_IbJM2_uA8aBp0uMu9EoPVwBARTf2o0kOjst9rk6k96Hd5l9dafyz3PapfBvZeFDewYq3CvNXTI1D7pbnBhLQkhT9zLnk6Le-PqhOjAaFLLNEqHP38zppyTiYByLP5CvUsJIqEq2aZhLEJFLvNZ96oud8cYkfvmhoPY2RqIQ6wmUZCYSMW3Wu2tJMkQghH62C0RHR9DDpsO4GfdwJdSGK5-o9MAogXORph3Avi1foNY2P1uP4iO4_IN5rRrrT3uhhvrnpNSTPpDqowsdfV8RIq4aUK5do_urVGXxlDgkGieLg"
- :title: "John Cowden FSM School Part III ANZO"
  :video_id: "62510c43617d36d59b3160bbb3d0ce65"
  :nbf: 0
  :exp: 0
  :short_url_key: "johncowdenfsmschoolpartiiianzo"
  :signed_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4In0.eyJzdWIiOiI2MjUxMGM0MzYxN2QzNmQ1OWIzMTYwYmJiM2QwY2U2NSIsImtpZCI6IjE1Y2FiMDY4YzhhMmU1OWRjYjk1ZGZkMzVkZTdiNjI4IiwiZXhwIjoiMTYxMjM1NjY0OSIsIm5iZiI6IjE2MTIzNDk0NDkifQ.tFwWE0VD0fLROqJylhrcgnr6ordLwEAUutJ468huKkKf9ddtdjss5FMNXaEO8r72IUcRb5RlQxthVaKzYGyxL9tz4dRTLOtcedViADXeswFA89eUcCUu4nFs4uUeirib3TlkspprI2bPxf-ROcd-uL3o9163KvERNfn6JbH09U5eM3tYmkanq4gcRpDo0PhkYZiJXjM3u2E8JViCeVJ5g4JJWC7LS4B8d_-Fm89dEp0AUK1RoVrlOr6QBGFb7KuGgM2me3qmplT68yWgjMDB_UXJoN_zf2th2CKMAuhtV1I_dW148WbMjfDNUITqNAz5_ZZCtOlEqRsLiomcuia-yQ"
