---
:surveys:
- :id: 'fsmschool'
  :label_1: "1. How are you going to use this data from today’s Seminar?"
  :label_2: "2. What did you decide today?"
  :label_3: "3. What subjects do you want to cover next?"
  :label_4: "4. Name out 3 people who you can contact and bring to this FSM School."
  :label_5: "5. Anything else you would like to communicate?"
  :label_6: "6. Are there any selectees you need help with? Please specify which Org"
  :label_phone: "Cell Number"
  :label_name: "Full Name"
  :label_training: "Training Level"
  :label_processing: "Processing Level"
- :id: 'admintools'
  :label_1: "1. What is the Goal you set?"
  :label_2: "2. What is the Product or Products you worked out?"
  :label_3: "3. What is the Stat or Stats you worked out?"
  :label_4: "4. What did you take away from today's seminar that you found useful?"
  :label_5: "5. Did the seminar meet your expectations? Or was there something else you would have liked covered?"
  :label_6: "6. What decisions have you made about your Bridge & what are the next actions you plan to take?"
  :label_phone: "Cell Number"
  :label_name: "Full Name"
  :label_training: "Training Level"
  :label_processing: "Processing Level"
